version: "3.9"

name: my-microservices
services:
  code-executor:
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: always
    env_file:
      - .env
    networks:
      my-ms:

networks:
  my-ms:
    driver: bridge
