version: "3.9"
name: hackathon

services:
  code-executor:
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - static:/static:mode=777
    restart: always
    env_file:
      - .env
    networks:
      my-ms:

networks:
  my-ms:
    driver: bridge

volumes:
  static: